name: Terraform Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'terraform/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]

jobs:
  terraform-check:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      
      - name: Terraform Format Check
        working-directory: ./terraform/eks/minimal
        run: |
          echo "Checking Terraform formatting..."
          terraform fmt -check -recursive || echo "⚠️ Some files need formatting"
        continue-on-error: true
      
      - name: Terraform Init (Validation Mode)
        working-directory: ./terraform/eks/minimal
        run: |
          echo "Initializing Terraform in validation mode..."
          terraform init -backend=false
      
      - name: Terraform Validate
        working-directory: ./terraform/eks/minimal
        run: |
          echo "Validating Terraform configuration..."
          terraform validate
      
      - name: Validation Success
        run: |
          echo "✅ Terraform validation completed successfully!"
          echo "Infrastructure code is valid and ready for deployment."

  documentation-check:
    name: Verify Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Check Required Documentation Files
        run: |
          echo "Checking for required documentation..."
          
          if [ -f "README.md" ]; then
            echo "✅ README.md found"
          else
            echo "❌ README.md missing"
            exit 1
          fi
          
          if [ -f "docs/DEPLOYMENT_GUIDE.md" ] || [ -f "DEPLOYMENT_GUIDE.md" ]; then
            echo "✅ Deployment guide found"
          else
            echo "⚠️ Deployment guide not found"
          fi
          
          echo ""
          echo "✅ Documentation check completed"
      
      - name: Check Terraform Files
        run: |
          echo "Checking Terraform file structure..."
          
          if [ -d "terraform" ]; then
            echo "✅ Terraform directory exists"
            find terraform -name "*.tf" | head -10
          else
            echo "❌ Terraform directory missing"
            exit 1
          fi
      
      - name: Check Kubernetes Manifests
        run: |
          echo "Checking for Kubernetes manifests..."
          
          if [ -d "kubernetes" ] || [ -d "src" ]; then
            echo "✅ Kubernetes/Application manifests found"
          else
            echo "⚠️ No manifest directories found"
          fi
          
          echo ""
          echo "✅ Project structure validated"

  summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [terraform-check, documentation-check]
    
    steps:
      - name: Display Summary
        run: |
          echo "╔════════════════════════════════════════════╗"
          echo "║   InnovateMart EKS Validation Complete    ║"
          echo "╚════════════════════════════════════════════╝"
          echo ""
          echo "✅ Terraform configuration validated"
          echo "✅ Documentation verified"
          echo "✅ Project structure confirmed"
          echo ""
          echo "Note: Infrastructure is deployed manually."
          echo "This workflow validates code quality only."
