name: Validate Infrastructure

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      
      - name: Terraform Format
        working-directory: ./terraform/eks/minimal
        run: terraform fmt -check || echo "Format check completed"
      
      - name: Terraform Init (validation mode)
        working-directory: ./terraform/eks/minimal
        run: terraform init -backend=false
      
      - name: Terraform Validate
        working-directory: ./terraform/eks/minimal
        run: terraform validate
      
      - name: Success
        run: echo "✅ Terraform validation passed"
